### ISSUE TITLE
Mocking weight data using the breakbeam data

### ISSUE THREAD

**Issue by uci-mars** [zotbins/ZotBins-Management-Client#18]
Create an endpoint to get an array of breakbeam data given a startTime and endTime. Since the weight sensor is currently not available, we need to use the breakbeam data to mock the weight data. We need to seperate the time period by hour and find the total breakbeam instance per hour.

Let each **breakbeam instance == 10g** of waste and the first instance in the array be 0g. Over time the "waste data" should increment at every breakbeam instance.

**Realtime:** To generate the realtime data we would need to pretend that the waste bin is full at a certain point. Let that point be **full bin == 1200g of waste.** Whenever the bin is full, its weight data should be 0g.

**Cumulative (rate of change):** Depending on the length of the time period, we need to divide the time into different sections. (i.e. Last 6 months == monthly, Last month == weekly) Get the total of "waste data" per section and then calculate the rate of change between each two points.

refer to notes in the slack channel

**Comment by okyang** [comment]
Yeah @gracechoe and I could easily add this API.

>  Whenever the bin is full, its weight data should be 0g.

Shouldn't be empty when it is 0 grams?

**Comment by uci-mars** [comment]
Oh, I meant the counter should reset to counter after the cumulative weight in realtime reaches 1200g.

**Comment by caojoshua** [comment]
Moved this to systems design team. https://github.com/zotbins/ZotBinsAPI/issues/6
