### ISSUE TITLE
Implement a collection of progress bar to display the fullness of each bins on overall page

### ISSUE THREAD

**Issue by uci-mars** [zotbins/ZotBins-Management-Client#20]
![image](https://user-images.githubusercontent.com/32443134/81512847-b544d600-92d8-11ea-9dca-2c712eed75d8.png)

**Comment by uci-mars** [comment]
https://ant.design/components/progress/#header

**Comment by primalpop** [comment]
Just saw this after commenting on Jesse's proposal. I like the progress bars on this better while I think showing tiny bins along with it might be nice if it is not too difficult.
