### ISSUE TITLE
Plot Diversion Rate More Accurately

### ISSUE THREAD

**Issue by jessechong** [zotbins/ZotBins-Management-Client#32]
This is what we have before:
![image](https://user-images.githubusercontent.com/44284982/96655346-18a84a80-12f2-11eb-82af-b640ce8a71b2.png)

Its a placeholder and not representative of how we should actually visualize diversion rate.

FYI diversion rate is defined as (recyclables+compost)/(recyclables+compost+landfill).

Since it looks like we are visualizing data based off of a set of bins (compost, landfill, recycling) we can always calculate the diversion rate. (I think the idea is that ZotBins is always deployed in a set-- however, that is something we can worry about later).

I think the best way to visualize diversion rate is to have a chart plotting "landfill" vs "diversion rate". For example, see the following diagram:
![image](https://user-images.githubusercontent.com/44284982/96655307-ff9f9980-12f1-11eb-949c-a0caff5cb93b.png)

Since all our values are hardcoded and our "weight" chart only has Jan, Feb, March, then we can do the same for our diversion rates. For now, let's just plot "Jan", "Feb", and "Mar".

**Please finish this by our next subgroup meeting! As always, let me know if you need more time**

**Comment by jessechong** [comment]
As per our meeting today, remove the "total landfill weight" so that we only pllot diversion rate

Feel free to use linechart or bar graphs-- i think i prefer what u have now tho!

**Comment by jessechong** [comment]
Also change the fonts to what the web app is using

**Comment by psgbhavani** [comment]
Removed the total "landfill weight" part and changed the fonts to a 'sans-serif' font.
