### ISSUE TITLE
Gallery Page Fix

### ISSUE THREAD

**Issue by jessechong** [zotbins/ZotBins-Management-Client#34]
Not displaying pics as before, will need to collab with Grace/Systems team on this.

**Comment by jessechong** [comment]
based on our discussion Let's rename this to "Bin Snapshots". "Gallery" is a little ambiguous

**Comment by psgbhavani** [comment]
Details on how to run server for the images:
- Open a cmd window and cd into the server folder. Run the server using ` nodemon ./bin/www `(simultaneously w/ running client)
- Next, open another cmd window and cd into the client folder. Run the app using `npm start `

**Comment by jessechong** [comment]
For some reason, i couldn't run the server using just "nodemon". Based on this article - https://stackoverflow.com/questions/35530930/nodemon-not-working-bash-nodemon-command-not-found 

I tried using "npx nodemon" and that worked for me. it automatically starts "./bin/www" without me typing it out so i believe we dont need to specify

**Comment by jessechong** [comment]
Closed. Renamed "Gallery" -> "Bin Snapshots" and added the "npx nodemon" cmd to readme.
[https://github.com/zotbins/ZotBins-Management-Client/commit/51dc4c10b48469f06175adeaaaa15786ee9790ad](https://github.com/zotbins/ZotBins-Management-Client/commit/51dc4c10b48469f06175adeaaaa15786ee9790ad )
