### ISSUE TITLE
Implement Realtime Data card component

### ISSUE THREAD

**Issue by uci-mars** [zotbins/ZotBins-Management-Client#9]
Hardcoded values for now since db isn't storing data for fullness/weight yet

<img width="622" alt="Realtime data component" src="https://user-images.githubusercontent.com/32443134/75069183-80796d80-54a5-11ea-985f-26144affcf0f.png">

**Comment by uci-mars** [comment]
https://ant.design/components/statistic/

**Comment by psgbhavani** [comment]
Is this any different than the CardVisualFeature?

**Comment by uci-mars** [comment]
Yes, I didn't realized I made a duplicate task for this. 😅
